---

# https://rancher.com/docs/k3s/latest/en/advanced/#auto-deploying-manifests
- name: Ensure auto-deploying manifests are copied to the primary controller
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ k3s_server_manifests_dir }}/{{ item | basename | replace('.j2','') }}"
    mode: 0644
  loop: "{{ k3s_server_manifests_templates }}"
  when:
    - k3s_server_manifests_templates | length > 0
    - cni_provider == 'calico'

- name: Ensure auto-deploying manifests are downloaded to the primary controller
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ k3s_server_manifests_dir }}/{{ item.filename | default(item.url | basename) }}"
    mode: 0644
  loop: "{{ k3s_server_manifests_urls }}"
  when:
    - not ansible_check_mode
    - k3s_server_manifests_urls | length > 0
    - cni_provider == 'calico'


