---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: reset
    - { role: helm, tags: uninstall, "uninstall":true }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: helm, tags: uninstall, "uninstall":true }
