apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: elasticsearch 
  namespace: monitoring 
spec:
  interval: 5m0s
  path: ./live-infra/stagging
  prune: true
  sourceRef:
    kind: GitRepository
    name: elasticsearch 
  validation: client
