---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    flux_bin_path: /usr/local/bin/flux

  vars_files:
    - ../../defaults/main.yml

  tasks:

    - name: Check flux version.
      command: "{{ flux_bin_path }} --version"
      changed_when: false
      register: flux_verify_version

    - name: Verify flux's version is {{ flux_version }}.
      assert:
        that:
          - flux_version in flux_verify_version.stdout
