k3s_config_file: "/etc/rancher/k3s/config.yaml"
k3s_config_yaml_d_dir: "/etc/rancher/k3s/config.yaml.d"


##
# Agent Configuration
##

# https://rancher.com/docs/k3s/latest/en/installation/install-options/agent-config/#node
k3s_agent: []
