---
# See available releases: https://github.com/helm/helm/releases/
# Specific settings for Helm deployment on master node 
helm_version: 'v3.2.1'
helm_platform: linux
helm_arch: arm64
helm_bin_path: /usr/local/bin/helm

# Specify where charts should be copied on master node
#
helm_chart_values_path: /home/pi/repos/helm-charts-values

# List of avaible charts to deploy, comment the lines below to select 
# the components that will be deployed

helm_chart_repositories:
  metallb: https://metallb.github.io/metallb
    

helm_repository_chart_deployment:
  - repo_name: metallb 
    repo_deployment_name: metallb 
